apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-world
  labels:
    app: nginx-hello-world
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32042
    protocol: TCP
  selector:
    app: nginx-hello-world
